# Generated by Django 6.0.6 on 2026-06-13 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='Комментарии отсутствуют', max_length=256, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(max_length=256, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Самовывоз'), ('CR', 'Курьерская доставка'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=2, verbose_name='Тип доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество в заказе')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка')),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.clothe', verbose_name='Одежда')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='clothes',
            field=models.ManyToManyField(through='orders.PosOrder', to='catalogue.clothe', verbose_name='Одежда'),
        ),
    ]
