# Generated by Django 6.0.6 on 2026-06-09 07:13

import catalogue.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Необходимо в поле указать название категории', max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, default='Отсутствует', help_text='Указывайте описание категории, если считаете, что категория неочивидна', max_length=512, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Необходимо в поле указать название коллекции', max_length=255, unique=True, verbose_name='Название коллекции')),
                ('description', models.TextField(blank=True, default='Отсутствует', help_text='Подробно опишите добавляемую коллекцию, чтобы пользователи могли ознакомиться с ней', max_length=1024, null=True, verbose_name='Описание коллекции')),
                ('year', models.PositiveIntegerField(default=catalogue.models.get_current_year, help_text='Укажите год выхода коллекции', null=True, verbose_name='Год выхода коллекции')),
                ('season', models.CharField(choices=[('WI', 'Зима'), ('SP', 'Весна'), ('SU', 'Лето'), ('AU', 'Осень')], default=catalogue.models.get_current_season, help_text='Выберите время года, когдая вышла коллекция или же под какое время года данная коллекция', max_length=2, verbose_name='Время года выхода коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название одежды', max_length=100, verbose_name='Название одежды')),
                ('description', models.TextField(default='Отсутствует', help_text='Укажите подробное описание одежды', max_length=1024, null=True, verbose_name='Описание одежды')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость одежды, вплоть до копеек', max_digits=8, verbose_name='Стоимость одежды')),
                ('color', models.CharField(help_text='Укажите цвет одежды', max_length=100, verbose_name='Цвет одежды')),
                ('size', models.PositiveSmallIntegerField(help_text='Укажите размер одежды', verbose_name='Размер одежды')),
                ('photo', models.ImageField(blank=True, default='img/no-photo.jpg', help_text='Выберите и загрузите изображение одежды со своего компьютера', null=True, upload_to='img/%Y/%m/%d', verbose_name='Изображение одежды')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Наличие одежды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления одежды')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения одежды')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.category', verbose_name='Категория')),
                ('collection', models.ManyToManyField(to='catalogue.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
            },
        ),
    ]
